# Generated by Django 5.2.6 on 2025-09-12 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=255)),
                ('cantidad_medicinas', models.IntegerField()),
                ('fecha', models.DateField()),
                ('efectividad', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.CharField(max_length=50)),
                ('cada', models.CharField(max_length=50)),
                ('durante', models.CharField(max_length=50)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='miApp.receta')),
            ],
        ),
    ]
