# Generated by Django 5.2.6 on 2025-09-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='efectividad',
            field=models.IntegerField(),
        ),
    ]
