# Generated by Django 5.2.6 on 2025-09-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='img_id',
            field=models.CharField(default=''),
        ),
    ]
