# Generated by Django 5.2.6 on 2025-09-12 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_alter_receta_efectividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='cantidad_medicinas',
        ),
    ]
