# Generated by Django 5.2.6 on 2025-09-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_medicamento_img_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='img_id',
        ),
    ]
