# Generated by Django 5.2.6 on 2025-09-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_remove_receta_cantidad_medicinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='efectividad',
            field=models.IntegerField(default=0),
        ),
    ]
