# Generated by Django 5.2.6 on 2025-09-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0004_alter_receta_efectividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
