# Generated by Django 5.2.6 on 2025-09-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0005_receta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='lugar',
            field=models.CharField(null=True),
        ),
    ]
