# Generated by Django 5.2.6 on 2025-09-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0006_receta_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='img',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
