# Generated by Django 5.2.6 on 2025-09-18 23:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0007_medicamento_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='lugar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
