# Generated by Django 5.2.6 on 2025-09-19 00:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0008_alter_medicamento_img_alter_receta_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, verbose_name='image'),
        ),
    ]
